### ISSUE TITLE
Improve testing code and introduce snapshots

### ISSUE THREAD

**Issue by abdulhannanali** [snyk/nodejs-lockfile-parser#113]
The testing code right now is spread between node-tap and jest. Moreover, the process of introducing properties and updating fixtures is quite cumbersome and not for everyone. 

This could be improved, in order to make the testing seamless and smoother. I propose following changes.

- Migration of all tests to Jest
- Use of snapshotting for fixture expected dependency trees comparison, it would give us better performance along with easier management and updating
- Further modularization of the test code

**Comment by lili2311** [comment]
hi @abdulhannanali thanks for raising this,  we are indeed in the process of migrating to `jest`. Completely with you on the snapshots :)

**Comment by abdulhannanali** [comment]
Great to hear that! Hope the migration goes well. :+1:
