### ISSUE TITLE
yarn2 and node 8 support

### ISSUE THREAD

**Issue by patsplat** [snyk/nodejs-lockfile-parser#90]
Yarn 2 support was [removed](https://github.com/snyk/nodejs-lockfile-parser/pull/85) because Yarn 2 requires `node>10`

It is not necessary to depend on `@yarnpkg/core` to parse the lockfile.  The Yarn 2 lockfile is yaml and should be parseable by `yaml`.  The `yaml` dependency only [requires](https://github.com/eemeli/yaml/blob/master/package.json#L94) `node>6`.  It seems the main issue would be forking `parseDescriptor` and `parseRange` into `nodejs-lockfile-parser`.

What is the appetite for a PR modifying #85 to bring back yarn2 support in a way that also supports node 8?

**Comment by abdulhannanali** [comment]
Looks like this should be closed, since there's already Yarn v2 support

**Comment by orsagie** [comment]
Hi @patsplat, Sorry we never got back to you. We will do a better job of looking at issues on our repos in future.

We recently re-added Yarn2 support to the parser (soon to be done in CLI too: https://github.com/snyk/snyk/pull/1794) as node 8 support was discontinued for our CLI.
