### ISSUE TITLE
[Feature Request] Add support for integrity and resolved properties for dependency

### ISSUE THREAD

**Issue by abdulhannanali** [snyk/nodejs-lockfile-parser#98]
lockfile-lint needs support for yarn v2 lockfile as mentioned in https://github.com/lirantal/lockfile-lint/issues/101 .Since this repo  already has good support for Yarn v2 , we would like to use this repo in order to eliminate all in-house lockfile parsing logic. However, lockfile-lint requires `integrity` and `resolved` properties for dependencies as  well in order to perform current and any future potential checks. 

I would like to know if the authors would be willing to accept a PR to add support for these properties. 

/cc @lirantal

**Comment by orsagie** [comment]
Hi @abdulhannanali
We would be glad to accept a PR that adds these properties to the parser. The PR will need to be tested with our CLI: https://github.com/snyk/snyk.
